const c = {
  SET_MODELS: 'SET_MODELS',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_FULFILLED: 'REGISTER_USER_FULFILLED',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_FULFILLED: 'LOGIN_USER_FULFILLED',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_AUTH_USER: 'SET_AUTH_USER',

  LOAD_ENTERTAINMENTS: 'LOAD_ENTERTAINMENTS',
  LOAD_ENTERTAINMENTS_FULFILLED: 'LOAD_ENTERTAINMENTS_FULFILLED',
  LOAD_ENTERTAINMENT: 'LOAD_ENTERTAINMENT',
  LOAD_ENTERTAINMENT_FULFILLED: 'LOAD_ENTERTAINMENT_FULFILLED',
  CREATE_ENTERTAINMENT: 'CREATE_ENTERTAINMENT',
  CREATE_ENTERTAINMENT_FULFILLED: 'CREATE_ENTERTAINMENT_FULFILLED',
  UPDATE_ENTERTAINMENT: 'UPDATE_ENTERTAINMENT',
  UPDATE_ENTERTAINMENT_FULFILLED: 'UPDATE_ENTERTAINMENT_FULFILLED',
  DESTROY_ENTERTAINMENT: 'DESTROY_ENTERTAINMENT',
  DESTROY_ENTERTAINMENT_FULFILLED: 'DESTROY_ENTERTAINMENT_FULFILLED',
  SORT_ENTERTAINMENTS: 'SORT_ENTERTAINMENTS',

  LOAD_PLACE: 'LOAD_PLACE',
  LOAD_PLACE_FULFILLED: 'LOAD_PLACE_FULFILLED',
  LOAD_PLACES: 'LOAD_PLACES',
  LOAD_PLACES_FULFILLED: 'LOAD_PLACES_FULFILLED',
  CREATE_PLACE: 'CREATE_PLACE',
  CREATE_PLACE_FULFILLED: 'CREATE_PLACE_FULFILLED',
  UPDATE_PLACE: 'UPDATE_PLACE',
  UPDATE_PLACE_FULFILLED: 'UPDATE_PLACE_FULFILLED',
  DESTROY_PLACE: 'DESTROY_PLACE',
  DESTROY_PLACE_FULFILLED: 'DESTROY_PLACE_FULFILLED',

  REMOVE_PLACE_PHOTO: 'REMOVE_PLACE_PHOTO'

}

export default c
